quouch/quouch

- .github/workflows/pr-check.yml
- .gitpod.yml
- Gemfile
- Gemfile.lock
Use [action-rubocop](https://github.com/reviewdog/action-rubocop) instead of manually running rubocop. This adds annotations to changed files, making it easier to find and fix the errors.
> use rubocop action

- .rubocop.yml
- db/migrate/20240712140039_initialize_jti_for_existing_users.rb
- db/schema.rb
- db/seeds.rb
I had an issue locally where the JTI did not exist in a user. I don't know why the migration worked in the first place! This should fix it.
@lisbethpurrucker I don't know if there's a way to fix/remove a migration. If there's one that's safe, I'm happy to do that instead.
> fix: add migration for users without JTI

- app/views/devise/confirmations/new.html.erb
Came upon this inconsistent form design when checking all the session related actions.
> remove email labels from new confirmation form, add placeholder text

- app/views/devise/passwords/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_header.html.erb
Fixes the issue with flash messages not being shown properly in the following cases:
- when you enter a wrong password on log in, it adds a “invalid email or password” as random text, with every click it adds it again and again. if you then actually log in successfully, it stays on the page.
- when you log out, it should display a flash “successfully logged out” and it displays nothing
- when you click on forgot password? and you request an email to reset the password, the email is sent but no flash is displayed/no redirect happens. it throws a POST 500 error for turbo
This is the only fix I found, based on [this StackOverflow post](https://stackoverflow.com/questions/36214082/rails-devise-nil-location-provided-cant-build-uri-on-password-reset)
> fix: add data-turbo:false to session calls to display flash message

- .github/ISSUE_TEMPLATE/01_bug_report.md
- .github/ISSUE_TEMPLATE/02_feature_request.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- Add code of conduct file
>Adopt a code of conduct to define community standards, signal a welcoming and inclusive project, and outline procedures for handling abuse.
From [GitHub Docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)
- Add PR template
- Add Issue templates
This are some of the best practices when collaborating in GitHub. It's specially going to be useful if we at any point go decide to open source this!
> Add Code of Conduct and other collaboration documents

- Gemfile
- Gemfile.lock
- Guardfile
- app/controllers/concerns/couches_concern.rb
- app/models/couch.rb
- test/controllers/couches_concern_test.rb
- test/factories/users.rb
- test/helpers/sign_in_helper.rb
- test/helpers/user_helper.rb
- test/test_helper.rb
Issue number: resolves #67 
---------
The interaction between characteristic and location filtering was failing. The problem seems to be that `pg_search` introduces a clause to order by rank, and the `group` and `having` clause wanted this column to be referenced in a group. When adding this column to a group, it caused the results to be aggregated, breaking the pagination.
The solution I found required removing the ranking from the `search_by_location` method. We can discuss if this is something that we need and how we can improve our filtering!
- Add tests for filtering couches
- Add `guard` gem to better run tests locally (watch functionality)
- Add [`shoulda`](https://github.com/thoughtbot/shoulda) for added test assertions
> [#67] fix: repair interaction between characteristics and location filter

- app/assets/stylesheets/components/_booking-form.scss
- app/assets/stylesheets/components/_bookings.scss
- app/assets/stylesheets/components/_chat.scss
- app/assets/stylesheets/components/_host.scss
- app/assets/stylesheets/components/_plans.scss
- app/assets/stylesheets/components/_requests.scss
- app/assets/stylesheets/components/_user-form.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/partials/_errors.scss
- app/assets/stylesheets/partials/_footer.scss
There's a bunch of warnings from the CSS compilation run about using `flex-start` instead of `start` due to mixed support.
Error: `start value has mixed support, consider using flex-start instead`
> fix: move from start to flex-start

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_cookies.scss
- app/assets/stylesheets/pages/_general.scss
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/cookies.html.erb
- config/routes.rb
- test/system/cookies_test.rb
Issue number: resolves #92 
---------
Added a page for the Cookies text with some sample text.
Added the `cookies_eu` gem, which seems to work for getting the banner working.
> feat: add GDPR cookie banner [#92]

- app/models/user.rb
- test/controllers/concerns/couches_concern_test.rb
- test/controllers/concerns/registration_concern_test.rb
- test/helpers/user_helper.rb
- test/models/user_test.rb
- test/support/helpers/jwt_token_helper_test.rb
- test/system/users/registration_workflow_test.rb
Revert unless clause for validating `invited_by_id`, so that it's always checked.
Modify tests so they pass
> hotfix: remove complex `unless` clause for validation

- .github/workflows/pr-check.yml
We don't need security analysis on every pull request. On push to `main` is enough.
> fix(ci): do not run analysis on pull requests

- app/controllers/concerns/registration_concern.rb
- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- test/integration/controllers/users/registrations_controller_test.rb
- test/models/user_test.rb
- test/system/users/registration_workflow_test.rb
Issue number: resolves #94 and an unreported bug
---------
After merging the validation for invited_by_id field #98, the production app started experimenting flaky registration success.
The issue occurred when the invite code was saved as uppercase in the DB. This is only the case for @noravonbreitenbach's code, as it was not automatically generated. 
The solution was to manually update that code and make it lowercase. 
This PR restores all the changes we made to try and fix the issue, and adds extra logging and flash messages in case something like this happens again.
> fix: restore invited_by_id validation and add extra logging and error message

- app/controllers/concerns/registration_concern.rb
- app/controllers/invites_controller.rb
- test/controllers/concerns/registration_concern_test.rb
- test/integration/controllers/invites_controller_test.rb
Prevent errors when the invite code is surrounded by blank spaces.
> fix: strip user invite code to prevent issues

- app/controllers/concerns/registration_concern.rb
- app/controllers/invites_controller.rb
- app/helpers/invite_code_helper.rb
- app/models/user.rb
- test/controllers/concerns/couches_concern_test.rb
- test/controllers/concerns/registration_concern_test.rb
- test/helpers/invite_code_helper_test.rb
- test/integration/controllers/invites_controller_test.rb
- test/system/users/registration_workflow_test.rb
- test/test_helper.rb
Issue number: resolves #119
---------
Show the user an error message when the invite code has an invalid format. This should prevent invite code errors being flagged when the code is truly invalid.
> fix: Create invite_code_helper and add code check step

- .env.example
- config/environments/test.rb
- db/seeds.rb
- lib/tasks/populate.rake
- test/controllers/concerns/couches_concern_test.rb
- test/controllers/concerns/registration_concern_test.rb
- test/factories/users.rb
- test/fixtures/users.yml
- test/helpers/addresses.rb
- test/helpers/jwt_token_helper_test.rb
- test/helpers/sign_in_helper.rb
- test/helpers/user_helper.rb
- test/integration/controllers/api/v1/users/sessions_controller_test.rb
- test/integration/controllers/couches_controller_test.rb
- test/integration/controllers/users/registrations_controller_test.rb
- test/integration/couches_filter_test.rb
- test/models/couch_test.rb
- test/models/user_test.rb
- test/system/couches_filter_and_navigation_test.rb
- test/system/users/registration_workflow_test.rb
This should help the readability of test files. From the [ThoughtBot blog](https://thoughtbot.com/blog/remove-duplication-with-factorybots-traits):
> [FactoryBot](https://github.com/thoughtbot/factory_bot)’s traits are an outstanding way to DRY up your tests and factories by naming groups of attributes, callbacks, and associations in one concise area. 
I used this to replace `:test_user`, `:random_user` and `:test_user_couch`, which are names that in a way obscure what's going on. Instead, we can use `:user, :for_test, :with_couch` and explicitly name what we want the user to have.
Additionally, added an address helper class for formatting the address
- **Added `RAILS_ENV` to the example .env file**: this value can be used e.g. to simulate the test environment, but it defaults to …
> chore: refactor user factory to use traits

- config/initializers/sentry.rb
Sentry's pricing model is per-error. I forgot to disable logging from development after I was done with the tests!
> fix: remove development from sentry to reduce potential costs

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/bookings/index.html.erb
- app/views/bookings/requests.html.erb
- test/factories/bookings.rb
- test/factories/users.rb
- test/models/booking_test.rb
To avoid exceeding our SMTP limit, this PR implements the following changes:
- it as of now only sends reminder emails for pending bookings that lay in the future
- it sets pending bookings that lay in the past to expired in the same run
> fix: send reminders only for future bookings

- README.md
- app/helpers/address_helper.rb
- lib/tasks/convert_country_to_country_code.rake
- test/helpers/address_helper_test.rb
- test/tasks/correct_country_code_test.rb
Not all country codes have been properly set in the production DB, this script should fix that!
Context: 
We had a bunch of countries in the DB that were not correct, such as “DE” or “US”.
When we ran the migration from #132, all of the country names were copied to the country_code. This works for all the countries that were looking like “DE”, but the ones that were correct need to be fixed back to a valid country code. So if right now `country_code` is “Germany”, it needs to be converted to “DE”. This script should handle that.
What the script does is it checks if the `country == country_code` or if the `country_code` is empty, and then tries to find a country code from the country name, e.g from “Germany” try to get “DE”.
I do this by using the `ISO3166::Country` class which we were …
> feat: add country code fixer

- .github/workflows/pr-check.yml
- .github/workflows/security.yml
- .github/workflows/system-tests.yml
HOTFIX! All our actions are failing because the `setup-ruby` action is outdated.
I removed the pin to a specific commit sha as [recommended by their documentation](https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby#versioning)
> fix: unpin setup-ruby

- app/controllers/api/v1/bookings_controller.rb
- app/controllers/couches_controller.rb
- app/javascript/controllers/couch_search_controller.js
- app/javascript/controllers/display_filters_controller.js
- app/views/couches/_list.html.erb
- app/views/couches/index.html.erb
- app/views/couches/index.json.jbuilder
- app/views/partials/_couch.html.erb
- app/views/partials/_couches.html.erb
- lib/tasks/populate.rake
- test/schemas/messages_endpoint_test.rb
- test/schemas/reviews_endpoint_test.rb
Issue number: related to #69 
---
Remove the need to fetch couches using JavaScript. This way, the ruby controller is always the source of truth.
This should help building the map, as it eliminates the need to duplicate the same behaviour (and fetch twice!)
> fix: filter couches without fetching with JS

- app/controllers/messages_controller.rb
- app/services/amplitude_event_tracker.rb
I am passing the message and review instance directly to the amplitude event and am accessing the user id through that instance.
> define user id through instance

- app/controllers/subscriptions_controller.rb
- app/javascript/controllers/map_controller.js
- app/models/user.rb
- app/views/devise/mailer/reset_password_instructions.html.erb
- test/mailers/devise_mailer_test.rb
- test/models/user_test.rb
- test/system/couches/map_test.rb
Issue number: resolves [Sentry Issue](https://quouch.sentry.io/issues/8470391/?project=4507827525714000&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=14d&stream_index=11)
---
Some users didn't make it as far as having a first name. Let's use the email in that case for addressing them!
> fix: template error when user does not have a first name

- app/jobs/bookings_job.rb
- test/jobs/bookings_job_test.rb
Fix: send email to bookings couch, not the user who made the booking.
> change email to couches user not bookings user

- app/controllers/concerns/couches_concern.rb
- app/controllers/couches_controller.rb
- app/javascript/controllers/map_controller.js
- test/controllers/concerns/couches_concern_test.rb
- test/integration/controllers/couches_controller_test.rb
Issue number: resolves #69 and [this feedback](https://quouch.slack.com/archives/C068C8ES6NP/p1728293460653209)
---
Based on user feedback, make the exact address even more obscured.
All the points in this screenshot have the exact same coordinates, and none of the points are actually in that coordinate.
> fix: randomize latitude and longitude in rails

- app/jobs/bookings_job.rb
- test/jobs/bookings_job_test.rb
I had linked the url to the booking which is the one the guest itself can see, so I changed it to the show request url for the host.
> correct path

- app/controllers/users/registrations_controller.rb
> fix: missing context key

- app/controllers/chats_controller.rb
- test/integration/controllers/chats_controller_test.rb
Issue number: resolves #
---
Add conditional to chats show to only display chat to either sender or receiver.
> add statement to only show chat to user or sender
